-- =====================================================================
-- ATLAS  |  20_role_defaults.sql
-- Narrow the default rights so each role lands on a dashboard that
-- shows only its own work.
--
--   Purchase Executive   purchase only — raise, submit, send
--   Purchase Manager     purchase only — plus approve, rates, insights
--   Purchase HOD         purchase, stock, tasks, and the masters
--   Accounts             read-only across purchase
--   Admin / MD           everything, always
--
-- WARNING — THIS OVERWRITES THE ROLE SETTINGS YOU CURRENTLY HAVE.
-- It rewrites role_permissions from scratch. Personal exceptions on
-- individual people (profiles.perm_grant / perm_deny) are NOT touched.
--
-- If you have already tuned roles on the Roles page and are happy with
-- them, DO NOT RUN THIS FILE. Change what you want on the Roles page
-- instead — that is what it is for.
--
-- Run once, in Supabase → SQL Editor.
-- =====================================================================

begin;

delete from role_permissions
 where role in ('executive', 'manager', 'hod', 'accounts');

-- ---------------------------------------------------------------------
-- PURCHASE EXECUTIVE
-- Raises orders. Sees rate history, so they are not the last to know a
-- rate has moved.
--
-- Note: they do NOT get 'suppliers.view' or 'items.view'. Those rights
-- open the Suppliers and Items MASTER PAGES, which are for the HOD who
-- owns that data. Picking a supplier or an item while raising an order
-- still works for everyone — that reads the tables directly.
-- ---------------------------------------------------------------------

insert into role_permissions (role, permission_code)
select 'executive', code from permissions where code in (
  'po.view', 'po.create', 'po.submit', 'po.send',
  'compare.view', 'reports.view'
);

-- ---------------------------------------------------------------------
-- PURCHASE MANAGER
-- The same, plus the approving. No stock, no sales, no tasks — this
-- role exists to move orders through, and a dashboard cluttered with
-- other departments' figures makes that slower, not faster.
-- ---------------------------------------------------------------------

insert into role_permissions (role, permission_code)
select 'manager', code from permissions where code in (
  'po.view', 'po.create', 'po.submit', 'po.send',
  'po.approve', 'po.rate_edit',
  'compare.view', 'reports.view', 'insights.view'
);

-- ---------------------------------------------------------------------
-- PURCHASE HOD
-- Runs the function end to end, so also owns stock movement, the task
-- flow with other departments, and the supplier and item masters.
-- ---------------------------------------------------------------------

insert into role_permissions (role, permission_code)
select 'hod', code from permissions where code in (
  'po.view', 'po.create', 'po.submit', 'po.send',
  'po.approve', 'po.rate_edit',
  'compare.view', 'reports.view', 'insights.view',
  'inventory.view', 'godown.view', 'godown.edit',
  'transfers.view', 'transfers.create', 'transfers.approve',
  'tasks.view', 'tasks.create', 'tasks.verify', 'tasks.reports',
  'suppliers.view', 'suppliers.edit', 'items.view', 'items.edit'
);

-- ---------------------------------------------------------------------
-- ACCOUNTS
-- Reads, never writes. They need to confirm an order was approved
-- before releasing a payment, and nothing beyond that.
-- ---------------------------------------------------------------------

insert into role_permissions (role, permission_code)
select 'accounts', code from permissions where code in (
  'po.view', 'compare.view', 'reports.view'
);

commit;

-- ---------------------------------------------------------------------
-- Check what you just did:
--
--   select role, count(*) from role_permissions group by role order by role;
--
-- Expected: accounts 3, executive 6, hod 23, manager 9.
--
-- To give one person something their role does not have — a manager who
-- should also see Sales, say — do NOT edit this file. Open Masters →
-- Users, pick them, and tick it on the Rights tab. That is a personal
-- exception and it survives future changes to the role.
-- ---------------------------------------------------------------------
