/* ==================================================================
   ATLAS — import the three master files

   Reads the exports from the billing software and produces SQL you
   paste into Supabase. It does not connect to the database itself:
   30,000 rows through a browser on shop wifi is a bad idea, and a
   generated file can be read before it is run.

   Usage, from the project folder:

     node scripts/import-masters.mjs  path/to/STOCK_MASTER.xlsx \
                                      path/to/ITEM_MASTER.xls \
                                      path/to/SUPPLIER_MASTER.xls

   Writes import-<date>.sql next to the files.
   ================================================================== */

import * as XLSX from 'xlsx'
import { writeFileSync, readFileSync } from 'fs'

/* SheetJS's ESM build has no readFile in Node — it expects a buffer. */
const readBook = (path, opts) => XLSX.read(readFileSync(path), { type: 'buffer', ...opts })

const [stockPath, itemPath, supplierPath] = process.argv.slice(2)
if (!stockPath) {
  console.error('\n  node scripts/import-masters.mjs STOCK.xlsx [ITEM.xls] [SUPPLIER.xls]\n')
  process.exit(1)
}

const q = v => v === null || v === undefined || v === '' ? 'null'
  : `'${String(v).replace(/'/g, "''")}'`
const n = v => { const x = Number(v); return Number.isFinite(x) ? x : 'null' }
const d = v => {
  if (!v) return 'null'
  const dt = v instanceof Date ? v : new Date(v)
  return Number.isNaN(dt.getTime()) ? 'null' : `'${dt.toISOString().slice(0, 10)}'`
}

/* The export's "Colour" column actually holds the purchase type.
   Anything that is not one — blank, or the two stray real colours —
   is a Non CC purchase. */
const REAL_COLOURS = new Set(['CREAM', 'DARK CREAM'])
const purchaseType = v => {
  const t = String(v ?? '').trim().toUpperCase()
  if (!t || t === 'NA' || REAL_COLOURS.has(t)) return 'Non CC'
  return t
}

const out = []
out.push('-- generated by scripts/import-masters.mjs on ' + new Date().toISOString())
out.push('begin;')

/* ---------- item master ---------- */
if (itemPath) {
  const wb = readBook(itemPath)
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 })
  // the Crystal export shifts one column: Item, Unit, VAT, Cess, DiviName
  const body = rows.slice(1)
    .map(r => ({ name: String(r[0] ?? '').trim(), unit: r[1], vat: r[2], cess: r[3], divi: r[4] }))
    .filter(r => r.name)

  const seen = new Set()
  const values = body.filter(r => {
    const k = r.name.toUpperCase()
    if (seen.has(k)) return false      // 56 duplicate names in the export
    seen.add(k); return true
  }).map(r =>
    `(${q(r.name)}, ${q(r.unit || 'Nos')}, ${n(r.vat)}, ${n(r.cess)}, ${q(r.divi)})`)

  out.push(`\n-- item master: ${values.length} items`)
  for (let i = 0; i < values.length; i += 500) {
    out.push(`insert into item_master (name, unit, tax_pct, cess_pct, division_code)
select v.name, v.unit, v.tax, v.cess, dv.code
from (values\n  ${values.slice(i, i + 500).join(',\n  ')}
) as v(name, unit, tax, cess, divi)
left join divisions dv on upper(replace(dv.name,' ','')) = upper(replace(v.divi,' ',''))
on conflict do nothing;`)
  }
}

/* ---------- supplier master ---------- */
if (supplierPath) {
  const wb = readBook(supplierPath)
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 })
  const values = rows.slice(1)
    .map(r => ({ name: String(r[0] ?? '').trim(), a1: r[1], a2: r[2], place: r[3],
                 phone: r[4], mobile: r[5], reg: r[6] }))
    .filter(r => r.name)
    .map(r => `(${q(r.name)}, ${q(r.place)}, ${q(r.a1)}, ${q(r.a2)}, ${q(r.phone)}, ${q(r.mobile)}, ${q(r.reg)})`)

  out.push(`\n-- supplier master: ${values.length} suppliers`)
  for (let i = 0; i < values.length; i += 500) {
    out.push(`insert into supplier_master (name, place, address, address2, phone, mobile, gstin)
values\n  ${values.slice(i, i + 500).join(',\n  ')}
on conflict do nothing;`)
  }
}

/* ---------- stock master ---------- */
const wb = readBook(stockPath, { cellDates: true })
const sheet = wb.Sheets[wb.SheetNames[0]]
const stock = XLSX.utils.sheet_to_json(sheet)

let pieces = 0, value = 0
const lines = stock.map(r => {
  const qty = Number(r.Stock) || 0
  const amt = Number(r.Amount) || 0
  pieces += qty; value += amt
  const unitCost = qty > 0 ? amt / qty : 0
  return { r, qty, amt, unitCost }
})

/* Any division the file uses that the schema does not know about.
   The DIVISION CODE sheet turned out to be incomplete — the stock data
   used code 14 for perfume, which the sheet never listed, and the
   import failed on the foreign key. Rather than fix that one code and
   wait to be surprised again, insert whatever is in the data. */
const divs = [...new Set(stock.map(r => Number(r.DiviCode)).filter(Number.isFinite))]
out.push(`\n-- divisions present in this file: ${divs.join(', ')}`)
out.push(`insert into divisions (code, name, sort_order)
values\n  ${divs.map(d => `(${d}, 'Division ${d}', ${d})`).join(',\n  ')}
on conflict (code) do nothing;`)

// Every purchase type the file actually uses, after mapping blanks and
// the two stray colours to Non CC. Inserted first so the foreign key on
// barcodes.purchase_type holds.
const ptypes = [...new Set(stock.map(r => purchaseType(r.Colour)))]
out.push(`\n-- purchase types found in the stock file: ${ptypes.length}`)
out.push(`insert into purchase_types (code, label, sort_order)
values\n  ${ptypes.map(v => `(${q(v)}, ${q(v)}, 50)`).join(',\n  ')}
on conflict (code) do nothing;`)

out.push(`\n-- stock snapshot: ${lines.length} barcodes, ${Math.round(pieces)} pieces, ${Math.round(value)} at cost`)
out.push(`insert into stock_snapshots (taken_on, source_file, rows_loaded, total_pieces, total_value)
values (current_date, ${q(stockPath.split('/').pop())}, ${lines.length}, ${pieces.toFixed(2)}, ${value.toFixed(2)});`)

// barcodes — one row per batch, updated if seen before
const bc = lines.map(({ r, unitCost }) =>
  `(${q(r.BarCode)}, ${n(r.ItemCode)}, ${q(r.Item)}, ${n(r.SupCode)}, ${q(r.Supplier)}, ` +
  `${n(r.DiviCode)}, ${n(r.BrandCode)}, ${q(r.BrandName)}, ${n(r.PurRefNo)}, ${d(r.Arrival)}, ` +
  `${n(r.Qty)}, ${unitCost.toFixed(4)}, ${n(r.SalePrice)}, ${n(r.SelRateAfterDisc)}, ` +
  `${q(r.Size)}, ${q(purchaseType(r.Colour))}, ` +
  `${q(r.Design)})`)

out.push(`\n-- barcodes`)
for (let i = 0; i < bc.length; i += 400) {
  out.push(`insert into barcodes (barcode, item_code, item_name, supplier_code, supplier_label,
  division_code, brand_code, brand_name, purchase_ref, arrival_date,
  qty_received, unit_cost, sale_price, sale_price_disc, size,
  purchase_type, design)
values\n  ${bc.slice(i, i + 400).join(',\n  ')}
on conflict (barcode, purchase_ref) do update
  set last_seen = now(), unit_cost = excluded.unit_cost,
      sale_price = excluded.sale_price, sale_price_disc = excluded.sale_price_disc,
      purchase_type = excluded.purchase_type;`)
}

const sl = lines.map(({ r, qty, amt, unitCost }) =>
  `(${q(r.BarCode)}, ${n(r.PurRefNo)}, ${n(r.ItemCode)}, ${q(r.Item)}, ${n(r.SupCode)}, ` +
  `${n(r.DiviCode)}, ${n(r.Qty)}, ${qty}, ${n(r.StockPer)}, ${amt.toFixed(2)}, ` +
  `${unitCost.toFixed(4)}, ${n(r.SalePrice)}, ${d(r.Arrival)}, ${n(r.NoofDays)}, ` +
  `${q(purchaseType(r.Colour))})`)

out.push(`\n-- stock lines`)
for (let i = 0; i < sl.length; i += 400) {
  out.push(`insert into stock_lines (snapshot_id, barcode, purchase_ref, item_code, item_name,
  supplier_code, division_code, qty_received, qty_on_hand, stock_pct, value_at_cost,
  unit_cost, sale_price, arrival_date, days_held, purchase_type)
select s.id, v.* from (values\n  ${sl.slice(i, i + 400).join(',\n  ')}
) as v(barcode, purchase_ref, item_code, item_name, supplier_code, division_code,
       qty_received, qty_on_hand, stock_pct, value_at_cost, unit_cost, sale_price,
       arrival_date, days_held, purchase_type)
cross join (select id from stock_snapshots order by created_at desc limit 1) s;`)
}

// link the masters up now that both sides are loaded
out.push(`
-- ---------------------------------------------------------------
-- Recover the codes.
--
-- The two master exports have no code column, but the STOCK MASTER
-- carries both ItemCode and SupCode alongside the names — so the codes
-- come from there.
--
-- ItemCode to name is clean: no code carries two names. But 12 NAMES
-- carry more than one code (duplicates in the billing software), and 5
-- supplier names likewise. Those are matched on nothing: assigning one
-- of two possible codes at random is worse than leaving it null,
-- because a wrong code joins silently to the wrong product.
--
-- The query below only fills in names that map to exactly one code.
-- ---------------------------------------------------------------

update item_master im set code = b.item_code
  from (
    select item_name_key, min(item_code) as item_code
      from barcodes where item_code is not null
     group by item_name_key
    having count(distinct item_code) = 1        -- unambiguous only
  ) b
 where im.code is null and im.name_key = b.item_name_key;

update supplier_master sm set code = b.supplier_code
  from (
    select upper(btrim(supplier_label)) as key, min(supplier_code) as supplier_code
      from barcodes where supplier_code is not null
     group by 1
    having count(distinct supplier_code) = 1
  ) b
 where sm.code is null and sm.match_key = b.key;

-- what could not be matched, and why
select 'items with a code'          as what, count(*) from item_master where code is not null
union all
select 'items still without',              count(*) from item_master where code is null
union all
select 'item names with two codes',        count(*) from (
  select item_name_key from barcodes where item_code is not null
   group by 1 having count(distinct item_code) > 1) x
union all
select 'suppliers with a code',            count(*) from supplier_master where code is not null
union all
select 'suppliers still without',          count(*) from supplier_master where code is null;`)

out.push('\ncommit;')
out.push(`
-- check it landed
select 'items' t, count(*) from item_master
union all select 'items with a code', count(*) from item_master where code is not null
union all select 'suppliers', count(*) from supplier_master
union all select 'suppliers with a code', count(*) from supplier_master where code is not null
union all select 'barcodes', count(*) from barcodes
union all select 'stock lines', count(*) from stock_lines;

select * from v_stock_ageing order by sort_order;
select * from v_stock_by_purchase_type order by value desc nulls last;`)

/* ---------- write it out in pieces ----------

   The whole thing is around 9 MB. The Supabase SQL editor will not
   take that in one paste — it is a browser textarea, not a file
   loader. So it is split into parts small enough to paste, numbered in
   the order they must be run.

   Each part is a complete transaction on its own, so if part 7 fails
   parts 1 to 6 are still safely in.
*/

const MAX = 900_000                  // characters per part, comfortably pasteable
const stamp = new Date().toISOString().slice(0, 10)
const parts = []
let buf = []
let size = 0

for (const chunk of out) {
  if (size + chunk.length > MAX && buf.length) {
    parts.push(buf); buf = []; size = 0
  }
  buf.push(chunk); size += chunk.length
}
if (buf.length) parts.push(buf)

parts.forEach((body, i) => {
  const num = String(i + 1).padStart(2, '0')
  const head = [
    `-- ============================================================`,
    `-- ATLAS import ${stamp} — part ${i + 1} of ${parts.length}`,
    `--`,
    `-- Run the parts IN ORDER. Each is its own transaction, so a`,
    `-- failure in one leaves the earlier parts safely loaded.`,
    `-- ============================================================`,
    'begin;'
  ]
  const tail = ['commit;']
  const clean = body.filter(l => l !== 'begin;' && l !== 'commit;')
  writeFileSync(`import-${stamp}-part${num}.sql`,
                [...head, ...clean, ...tail].join('\n'))
})

console.log(`\n  ${parts.length} files written: import-${stamp}-part01.sql … part${String(parts.length).padStart(2,'0')}.sql`)
console.log(`  ${lines.length.toLocaleString('en-IN')} barcodes, ` +
            `${Math.round(pieces).toLocaleString('en-IN')} pieces, ` +
            `₹${(value / 1e7).toFixed(2)} crore at cost`)
console.log(`  run them in order in the Supabase SQL editor\n`)
