/* ==================================================================
   ATLAS — import the three master files

   Reads the exports from the billing software and produces SQL you
   paste into Supabase. It does not connect to the database itself:
   30,000 rows through a browser on shop wifi is a bad idea, and a
   generated file can be read before it is run.

   Usage, from the project folder:

     node scripts/import-masters.mjs  path/to/STOCK_MASTER.xlsx \
                                      path/to/ITEM_MASTER.xls \
                                      path/to/SUPPLIER_MASTER.xls

   Writes import-<date>.sql next to the files.
   ================================================================== */

import * as XLSX from 'xlsx'
import { writeFileSync, readFileSync } from 'fs'

/* SheetJS's ESM build has no readFile in Node — it expects a buffer. */
const readBook = (path, opts) => XLSX.read(readFileSync(path), { type: 'buffer', ...opts })

/* Which shop this file is for.

   This matters more than it looks. Without it every shop's file is
   stored as "no shop", they all collide on the one-snapshot-per-day
   rule, and each upload silently deletes the one before it. Ten shops
   would leave you with one.

     node scripts/import-masters.mjs NILAMBUR_STOCK.xlsx --shop NILAMBUR

   Leave --shop off only for a company-wide or godown file. */
const args = process.argv.slice(2)
const shopAt = args.indexOf('--shop')
const shop = shopAt >= 0 ? String(args[shopAt + 1] || '').trim().toUpperCase() : null
/* When --shop is absent, shopAt is -1, and "i !== shopAt + 1" becomes
   "i !== 0" — which quietly drops the filename. Only skip those two
   positions when the flag is actually there. */
const paths = shopAt >= 0
  ? args.filter((_, i) => i !== shopAt && i !== shopAt + 1)
  : args
const [stockPath, itemPath, supplierPath] = paths

if (!stockPath) {
  console.error('\n  node scripts/import-masters.mjs STOCK.xlsx [ITEM.xls] [SUPPLIER.xls] [--shop NILAMBUR]\n')
  process.exit(1)
}

const q = v => v === null || v === undefined || v === '' ? 'null'
  : `'${String(v).replace(/'/g, "''")}'`
const n = v => { const x = Number(v); return Number.isFinite(x) ? x : 'null' }
const d = v => {
  if (!v) return 'null'
  const dt = v instanceof Date ? v : new Date(v)
  return Number.isNaN(dt.getTime()) ? 'null' : `'${dt.toISOString().slice(0, 10)}'`
}

/* The export's "Colour" column actually holds the purchase type.
   Anything that is not one — blank, or the two stray real colours —
   is a Non CC purchase. */
const REAL_COLOURS = new Set(['CREAM', 'DARK CREAM'])
const purchaseType = v => {
  const t = String(v ?? '').trim().toUpperCase()
  if (!t || t === 'NA' || REAL_COLOURS.has(t)) return 'Non CC'
  return t
}

const out = []
out.push('-- generated by scripts/import-masters.mjs on ' + new Date().toISOString())
out.push('begin;')

/* ---------- item master ---------- */
if (itemPath) {
  const wb = readBook(itemPath)
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 })
  // the Crystal export shifts one column: Item, Unit, VAT, Cess, DiviName
  const body = rows.slice(1)
    .map(r => ({ name: String(r[0] ?? '').trim(), unit: r[1], vat: r[2], cess: r[3], divi: r[4] }))
    .filter(r => r.name)

  // 56 duplicate names in the export. The key must match the database's
  // name_key exactly — upper(btrim(name)) — or a pair that looks distinct
  // here collides there and the same error comes back.
  const seen = new Set()
  const values = body.filter(r => {
    const k = r.name.trim().toUpperCase()
    if (seen.has(k)) return false
    seen.add(k); return true
  }).map(r =>
    `(${q(r.name)}, ${q(r.unit || 'Nos')}, ${n(r.vat)}, ${n(r.cess)}, ${q(r.divi)})`)

  out.push(`\n-- item master: ${values.length} items`)
  for (let i = 0; i < values.length; i += 500) {
    out.push(`insert into item_master (name, unit, tax_pct, cess_pct, division_code)
select v.name, v.unit, v.tax::numeric, v.cess::numeric, dv.code
from (values\n  ${values.slice(i, i + 500).join(',\n  ')}
) as v(name, unit, tax, cess, divi)
left join divisions dv on upper(replace(dv.name,' ','')) = upper(replace(v.divi,' ',''))
on conflict (name_key) do update
  set unit = excluded.unit, tax_pct = excluded.tax_pct,
      cess_pct = excluded.cess_pct, division_code = excluded.division_code;`)
  }
}

/* ---------- supplier master ---------- */
if (supplierPath) {
  const wb = readBook(supplierPath)
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1 })
  /* 35 name+place combinations repeat in the export — M/S. DEEPIKA
     TEXTILES,PANIPAT appears five times. Postgres refuses an
     ON CONFLICT DO UPDATE that would touch the same row twice in one
     statement, so they have to be collapsed here.

     Keeping the row with the most filled in, since the duplicates are
     usually one complete record and several sparse ones. */
  const seenSup = new Map()
  rows.slice(1)
    .map(r => ({ name: String(r[0] ?? '').trim(), a1: r[1], a2: r[2], place: r[3],
                 phone: r[4], mobile: r[5], reg: r[6] }))
    .filter(r => r.name)
    .forEach(r => {
      const key = (r.name + ',' + String(r.place ?? '').trim()).toUpperCase().trim()
      const filled = [r.a1, r.a2, r.place, r.phone, r.mobile, r.reg]
        .filter(v => String(v ?? '').trim()).length
      const prev = seenSup.get(key)
      if (!prev || filled > prev.filled) seenSup.set(key, { ...r, filled })
    })

  const values = [...seenSup.values()]
    .map(r => `(${q(r.name)}, ${q(r.place)}, ${q(r.a1)}, ${q(r.a2)}, ${q(r.phone)}, ${q(r.mobile)}, ${q(r.reg)})`)

  out.push(`\n-- supplier master: ${values.length} suppliers`)
  for (let i = 0; i < values.length; i += 500) {
    out.push(`insert into supplier_master (name, place, address, address2, phone, mobile, gstin)
values\n  ${values.slice(i, i + 500).join(',\n  ')}
on conflict (match_key) do update
  set address = excluded.address, address2 = excluded.address2,
      phone = excluded.phone, mobile = excluded.mobile;`)
  }
}

/* ---------- stock master ---------- */
const wb = readBook(stockPath, { cellDates: true })
const sheet = wb.Sheets[wb.SheetNames[0]]
const stock = XLSX.utils.sheet_to_json(sheet)

/* 20 batches appear on more than one row — same barcode, same purchase
   reference, same item, same price, same arrival date, with the
   quantity split across the rows. Postgres will not let one statement
   update the same key twice, and dropping the extra rows would lose
   11,512 pieces worth about ₹16 L.

   So they are added together: quantities and value summed, everything
   else taken from the first row. Unit cost is recomputed from the
   combined figures rather than carried over from one of the parts. */
/* Some of these exports end with a totals row — blank barcode, totals
   in the quantity and amount columns. Counting it doubles the file. */
const body = stock.filter(r => String(r.BarCode ?? '').trim() !== '')
if (body.length !== stock.length) {
  console.log(`  ignored ${stock.length - body.length} totals row(s) at the bottom`)
}

const merged = new Map()
for (const r of body) {
  const key = `${r.BarCode}|${r.PurRefNo}`
  const prev = merged.get(key)
  if (!prev) {
    merged.set(key, { ...r, Qty: Number(r.Qty) || 0,
                      Stock: Number(r.Stock) || 0, Amount: Number(r.Amount) || 0 })
  } else {
    prev.Qty    += Number(r.Qty) || 0
    prev.Stock  += Number(r.Stock) || 0
    prev.Amount += Number(r.Amount) || 0
  }
}
const mergedRows = [...merged.values()]
if (mergedRows.length !== body.length) {
  console.log(`  merged ${body.length - mergedRows.length} split rows into their batch`)
}

/* A full godown master includes barcodes at zero stock. They matter:
   the godown created them and still holds the item, division and
   supplier, which is what classifies a sale.

   So every row goes into `barcodes` — that is the classification
   master. Only rows with stock go into `stock_lines`, which is the
   stock snapshot; a zero-stock row is not stock and would drag every
   stock report down with rows worth nothing. */
const withStock = mergedRows.filter(r => (Number(r.Stock) || 0) > 0)
const zeroStock = mergedRows.length - withStock.length
if (zeroStock > 0) {
  console.log(`  ${zeroStock.toLocaleString('en-IN')} barcodes at zero stock — ` +
              `kept for classification, left out of the stock figures`)
} else {
  console.log('  every row has stock. If this is the full godown master, the export')
  console.log('  still has a "stock greater than zero" filter on it — ask for it off,')
  console.log('  or sold-out barcodes stay unclassified on the sales reports.')
}

let pieces = 0, value = 0
const lines = withStock.map(r => {
  const qty = r.Stock
  const amt = r.Amount
  pieces += qty; value += amt
  const unitCost = qty > 0 ? amt / qty : 0
  // StockPer is recomputed too — the exported value belonged to one part
  r.StockPer = r.Qty > 0 ? (qty / r.Qty * 100) : 0
  return { r, qty, amt, unitCost }
})

/* Any division the file uses that the schema does not know about.
   The DIVISION CODE sheet turned out to be incomplete — the stock data
   used code 14 for perfume, which the sheet never listed, and the
   import failed on the foreign key. Rather than fix that one code and
   wait to be surprised again, insert whatever is in the data. */
const divs = [...new Set(mergedRows.map(r => Number(r.DiviCode)).filter(Number.isFinite))]
out.push(`\n-- divisions present in this file: ${divs.join(', ')}`)
out.push(`insert into divisions (code, name, sort_order)
values\n  ${divs.map(d => `(${d}, 'Division ${d}', ${d})`).join(',\n  ')}
on conflict (code) do nothing;`)

// Every purchase type the file actually uses, after mapping blanks and
// the two stray colours to Non CC. Inserted first so the foreign key on
// barcodes.purchase_type holds.
const ptypes = [...new Set(mergedRows.map(r => purchaseType(r.Colour)))]
out.push(`\n-- purchase types found in the stock file: ${ptypes.length}`)
out.push(`insert into purchase_types (code, label, sort_order)
values\n  ${ptypes.map(v => `(${q(v)}, ${q(v)}, 50)`).join(',\n  ')}
on conflict (code) do nothing;`)

out.push(`\n-- stock snapshot: ${lines.length} barcodes, ${Math.round(pieces)} pieces, ${Math.round(value)} at cost`)
// Clear any snapshot already loaded for today before making a new one,
// so re-running this part starts clean instead of colliding with the
// unique index. stock_lines cascade away with it.
// scoped to this shop, so loading Perinthalmanna does not wipe Nilambur
out.push(shop
  ? `delete from stock_snapshots where taken_on = current_date and shop_code = ${q(shop)};`
  : `delete from stock_snapshots where taken_on = current_date and shop_code is null;`)

out.push(`insert into stock_snapshots (taken_on, source_file, shop_code, shop_id,
  rows_loaded, total_pieces, total_value)
select current_date, ${q(stockPath.split('/').pop())}, ${q(shop)},
       (select id from shops where upper(btrim(name)) = ${q(shop)}
           or upper(btrim(code)) = ${q(shop)} limit 1),
       ${lines.length}, ${pieces.toFixed(2)}, ${value.toFixed(2)};`)

// barcodes — one row per batch, updated if seen before
// barcodes: EVERY row, with or without stock
const bc = mergedRows.map(r => {
  const q = Number(r.Stock) || 0
  const a = Number(r.Amount) || 0
  return { r, unitCost: q > 0 ? a / q : 0 }
}).map(({ r, unitCost }) =>
  `(${q(r.BarCode)}, ${n(r.ItemCode)}, ${q(r.Item)}, ${n(r.SupCode)}, ${q(r.Supplier)}, ` +
  `${n(r.DiviCode)}, ${n(r.BrandCode)}, ${q(r.BrandName)}, ${n(r.PurRefNo)}, ${d(r.Arrival)}, ` +
  `${n(r.Qty)}, ${unitCost.toFixed(4)}, ${n(r.SalePrice)}, ${n(r.SelRateAfterDisc)}, ` +
  `${q(r.Size)}, ${q(purchaseType(r.Colour))}, ` +
  `${q(r.Design)})`)

out.push(`\n-- barcodes`)
for (let i = 0; i < bc.length; i += 400) {
  out.push(`insert into barcodes (barcode, item_code, item_name, supplier_code, supplier_label,
  division_code, brand_code, brand_name, purchase_ref, arrival_date,
  qty_received, unit_cost, sale_price, sale_price_disc, size,
  purchase_type, design)
values\n  ${bc.slice(i, i + 400).join(',\n  ')}
on conflict (barcode, purchase_ref) do update
  set last_seen = now(), unit_cost = excluded.unit_cost,
      sale_price = excluded.sale_price, sale_price_disc = excluded.sale_price_disc,
      purchase_type = excluded.purchase_type;`)
}

const sl = lines.map(({ r, qty, amt, unitCost }) =>
  `(${q(r.BarCode)}, ${n(r.PurRefNo)}, ${n(r.ItemCode)}, ${q(r.Item)}, ${n(r.SupCode)}, ` +
  `${n(r.DiviCode)}, ${n(r.Qty)}, ${qty}, ${n(r.StockPer)}, ${amt.toFixed(2)}, ` +
  `${unitCost.toFixed(4)}, ${n(r.SalePrice)}, ${d(r.Arrival)}, ${n(r.NoofDays)}, ` +
  `${q(purchaseType(r.Colour))})`)

out.push(`\n-- stock lines`)
for (let i = 0; i < sl.length; i += 400) {
  /* Every column is cast explicitly rather than using v.*.
     Inside a VALUES list feeding a SELECT, a quoted literal like
     '2026-08-17' is typed as text, and Postgres will not put text into
     a date column. The plain INSERT ... VALUES form infers types from
     the target columns and does not have this problem, which is why the
     barcodes insert above works without casts. */
  out.push(`insert into stock_lines (snapshot_id, barcode, purchase_ref, item_code, item_name,
  supplier_code, division_code, qty_received, qty_on_hand, stock_pct, value_at_cost,
  unit_cost, sale_price, arrival_date, days_held, purchase_type, shop_code, shop_id)
select s.id,
       v.barcode,
       v.purchase_ref::int,
       v.item_code::int,
       v.item_name,
       v.supplier_code::int,
       v.division_code::int,
       v.qty_received::numeric,
       v.qty_on_hand::numeric,
       v.stock_pct::numeric,
       v.value_at_cost::numeric,
       v.unit_cost::numeric,
       v.sale_price::numeric,
       v.arrival_date::date,
       v.days_held::int,
       v.purchase_type,
       ${q(shop)},
       s.shop_id
from (values\n  ${sl.slice(i, i + 400).join(',\n  ')}
) as v(barcode, purchase_ref, item_code, item_name, supplier_code, division_code,
       qty_received, qty_on_hand, stock_pct, value_at_cost, unit_cost, sale_price,
       arrival_date, days_held, purchase_type)
cross join (select id from stock_snapshots
             where taken_on = current_date
               and coalesce(shop_code, '~') = coalesce(${q(shop)}, '~')
             order by created_at desc limit 1) s;`)
}

// link the masters up now that both sides are loaded
out.push(`
-- ---------------------------------------------------------------
-- Recover the codes.
--
-- The two master exports have no code column, but the STOCK MASTER
-- carries both ItemCode and SupCode alongside the names — so the codes
-- come from there.
--
-- ItemCode to name is clean: no code carries two names. But 12 NAMES
-- carry more than one code (duplicates in the billing software), and 5
-- supplier names likewise. Those are matched on nothing: assigning one
-- of two possible codes at random is worse than leaving it null,
-- because a wrong code joins silently to the wrong product.
--
-- The query below only fills in names that map to exactly one code.
-- ---------------------------------------------------------------

update item_master im set code = b.item_code
  from (
    select item_name_key, min(item_code) as item_code
      from barcodes where item_code is not null
     group by item_name_key
    having count(distinct item_code) = 1        -- unambiguous only
  ) b
 where im.code is null and im.name_key = b.item_name_key;

update supplier_master sm set code = b.supplier_code
  from (
    select upper(btrim(supplier_label)) as key, min(supplier_code) as supplier_code
      from barcodes where supplier_code is not null
     group by 1
    having count(distinct supplier_code) = 1
  ) b
 where sm.code is null and sm.match_key = b.key;

-- what could not be matched, and why
select 'items with a code'          as what, count(*) from item_master where code is not null
union all
select 'items still without',              count(*) from item_master where code is null
union all
select 'item names with two codes',        count(*) from (
  select item_name_key from barcodes where item_code is not null
   group by 1 having count(distinct item_code) > 1) x
union all
select 'suppliers with a code',            count(*) from supplier_master where code is not null
union all
select 'suppliers still without',          count(*) from supplier_master where code is null;`)

out.push('\ncommit;')
out.push(`
-- check it landed
select 'items' t, count(*) from item_master
union all select 'items with a code', count(*) from item_master where code is not null
union all select 'suppliers', count(*) from supplier_master
union all select 'suppliers with a code', count(*) from supplier_master where code is not null
union all select 'barcodes', count(*) from barcodes
union all select 'stock lines', count(*) from stock_lines;

select * from v_stock_ageing order by sort_order;
select * from v_stock_by_purchase_type order by value desc nulls last;`)

/* ---------- write it out in pieces ----------

   The whole thing is around 9 MB. The Supabase SQL editor will not
   take that in one paste — it is a browser textarea, not a file
   loader. So it is split into parts small enough to paste, numbered in
   the order they must be run.

   Each part is a complete transaction on its own, so if part 7 fails
   parts 1 to 6 are still safely in.
*/

const MAX = 900_000                  // characters per part, comfortably pasteable
const stamp = new Date().toISOString().slice(0, 10)
const parts = []
let buf = []
let size = 0

for (const chunk of out) {
  if (size + chunk.length > MAX && buf.length) {
    parts.push(buf); buf = []; size = 0
  }
  buf.push(chunk); size += chunk.length
}
if (buf.length) parts.push(buf)

parts.forEach((body, i) => {
  const num = String(i + 1).padStart(2, '0')
  const head = [
    `-- ============================================================`,
    `-- ATLAS import ${stamp} — part ${i + 1} of ${parts.length}`,
    `--`,
    `-- Run the parts IN ORDER. Each is its own transaction, so a`,
    `-- failure in one leaves the earlier parts safely loaded.`,
    `-- ============================================================`,
    'begin;'
  ]
  const tail = ['commit;']
  const clean = body.filter(l => l !== 'begin;' && l !== 'commit;')
  writeFileSync(`import-${stamp}-part${num}.sql`,
                [...head, ...clean, ...tail].join('\n'))
})

console.log(`\n  ${shop ? shop : 'company-wide / godown'}`)
console.log(`  ${parts.length} files written: import-${stamp}-part01.sql … part${String(parts.length).padStart(2,'0')}.sql`)
console.log(`  ${lines.length.toLocaleString('en-IN')} barcodes, ` +
            `${Math.round(pieces).toLocaleString('en-IN')} pieces, ` +
            `₹${(value / 1e7).toFixed(2)} crore at cost`)
console.log(`  run them in order in the Supabase SQL editor\n`)
