import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { db } from '../lib/db'
import { useMe } from '../App'
import Picker from '../components/Picker'

export default function NewPO() {
  const me = useMe()
  const nav = useNavigate()
  const [entities, setEntities] = useState([])
  const [suppliers, setSuppliers] = useState([])
  const [types, setTypes] = useState([])
  const [locked, setLocked] = useState(null)      // the only entity this user may use
  const [f, setF] = useState({ entity_id: '', supplier_id: '', purchase_type: '',
                               expected_date: '', remarks: '' })
  const [busy, setBusy] = useState(false)

  useEffect(() => {
    db.from('entities').select('*').eq('active', true).order('code')
      .then(({ data }) => {
        const allowed = (me.entity_ids?.length ? data.filter(e => me.entity_ids.includes(e.id)) : data) || []
        setEntities(allowed)
        if (allowed.length === 1) {
          setLocked(allowed[0])
          setF(v => ({ ...v, entity_id: allowed[0].id }))
        }
      })
    db.from('suppliers').select('*').eq('active', true).order('name')
      .then(({ data }) => setSuppliers(data || []))
    db.from('settings').select('value').eq('key', 'purchase_types').single()
      .then(({ data }) => setTypes(data?.value || []))
  }, [])

  async function start() {
    if (!f.entity_id) return alert('Choose the entity')
    if (!f.supplier_id) return alert('Choose the supplier')
    if (!f.purchase_type) return alert('Choose the purchase type')
    setBusy(true)
    const { data, error } = await db.from('purchase_orders').insert({
      entity_id: f.entity_id,
      supplier_id: f.supplier_id,
      purchase_type: f.purchase_type,
      expected_date: f.expected_date || null,
      remarks: f.remarks || null,
      created_by: me.id,
      status: 'draft'
    }).select().single()
    setBusy(false)
    if (error) return alert(error.message)
    nav('/orders/' + data.id)
  }

  return (
    <div className="mx-auto max-w-lg space-y-5">
      <div>
        <h1 className="text-xl font-bold">New purchase order</h1>
        <p className="text-sm text-slate2">Supplier and type first, then add items and split them across shops.</p>
      </div>

      <div className="card space-y-4 p-4">
        {locked ? (
          <div>
            <label>Entity</label>
            <div className="rounded-md border border-line bg-paper px-3 py-2 text-[15px]">
              {locked.name}
              <span className="ml-2 font-mono text-[11px] text-slate2">{locked.code}</span>
            </div>
          </div>
        ) : (
          <Picker label="Entity" placeholder="Choose entity"
            options={entities.map(e => ({ id: e.id, label: e.name, sub: e.code }))}
            value={f.entity_id} onChange={id => setF(v => ({ ...v, entity_id: id }))} />
        )}

        <Picker label="Supplier" placeholder="Search supplier master"
          options={suppliers.map(s => ({
            id: s.id, label: s.name,
            sub: [s.code, s.credit_days ? s.credit_days + ' days credit' : null].filter(Boolean).join(' · ')
          }))}
          value={f.supplier_id} onChange={id => setF(v => ({ ...v, supplier_id: id }))} />

        <div>
          <label>Purchase type</label>
          <div className="flex flex-wrap gap-2">
            {types.map(t => (
              <button key={t} type="button"
                onClick={() => setF(v => ({ ...v, purchase_type: t }))}
                className={'rounded-md border px-3 py-1.5 text-sm font-semibold ' +
                  (f.purchase_type === t
                    ? 'border-ink bg-ink text-white'
                    : 'border-line bg-white text-slate2')}>
                {t}
              </button>
            ))}
          </div>
        </div>

        <div>
          <label>Expected delivery</label>
          <input type="date" value={f.expected_date}
            onChange={e => setF(v => ({ ...v, expected_date: e.target.value }))} />
        </div>

        <div>
          <label>General remarks</label>
          <textarea rows={2} value={f.remarks}
            onChange={e => setF(v => ({ ...v, remarks: e.target.value }))}
            placeholder="Urgent / festival stock / replacement order" />
        </div>

        <button className="btn-dark w-full" onClick={start} disabled={busy}>
          {busy ? 'Creating' : 'Start adding items'}
        </button>
      </div>

      <p className="text-xs text-slate2">
        The order number is generated by the system when you submit for approval.
      </p>
    </div>
  )
}
